#!/usr/bin/env python3
"""Gate: no tracked text file is longer than an agent can read in one call.

    python3 scripts/gates/check_file_size.py [--root .] [--cap 2000]

    0 = every file within the cap    1 = a file over (or an exemption problem)
    2 = cannot judge

The Read tool shows 2000 lines by default. A file past that is read in
pieces, and the piece an agent did not ask for is where the defect it did not
see lives. The repository this gate was written in found its own 6074-line
selftest exactly this way, by pointing the gate at itself.

## Scope

Every file `git ls-files` reports, minus a short list, each entry here
because it is not prose an agent reads top to bottom:

  * anything with a NUL byte in its first 8 KB -- binary, not text;
  * `docs/generated/` -- regenerated by a script; the file to read is the one
    that generated it, and a diff against the output is not a document;
  * `node_modules/`, `vendor/`, `third_party/`, `.venv/` -- vendored or
    installed code nobody here wrote, split, or is expected to read whole;
  * lockfiles (`package-lock.json`, `poetry.lock`, `Cargo.lock`) -- one
    machine-written line per dependency, unsplittable and never read start to
    finish by a person;
  * `*.min.*` -- minified and generated, the same argument as a lockfile;
  * `*.svg` -- markup a renderer consumes, not prose an agent reads.

## Exemptions

`.claude/guards.json` may carry a `"file_size"` object:

    {"file_size": {"cap": 2000,
                   "exempt": [{"path": "shared/scripts/assess/selftest.py",
                               "reason": "being split; remove when it lands"}]}}

An exemption with an empty or missing reason is red -- the same rule
`check_docs_index.py` applies to `<!-- unrouted: reason -->`: a reason-less
exemption is a blanket exemption, because nothing distinguishes it from one
somebody meant to fill in later and never did. An exemption whose file has
since shrunk under the cap, or been deleted, is also red: it outlived the
reason it was added for, and a stale exemption is indistinguishable from one
nobody is watching.

No `.claude/guards.json`, or no `"file_size"` key inside it: the defaults
apply (cap 2000, no exemptions). A `.claude/guards.json` that exists but does
not parse as JSON is exit 2 -- this gate cannot tell whether an exemption is
present or not, so it must not guess.
"""

from __future__ import annotations

import argparse
import fnmatch
import json
import os
import shutil
import subprocess
import sys

DEFAULT_CAP = 2000

# Vendored/installed trees: not ours to split, and a target repository's own
# tooling put them there, not a person.
SKIP_DIR_NAMES = {"node_modules", "vendor", "third_party", ".venv"}
# Regenerated output -- the source worth reading is whatever produced it.
SKIP_PREFIXES = ("docs/generated/",)
# One machine-written line per dependency; nobody reads these start to finish.
SKIP_FILENAMES = {"package-lock.json", "poetry.lock", "Cargo.lock"}
# Generated/non-prose by construction.
SKIP_GLOBS = ("*.min.*", "*.svg")


def load_config(root):
    """(config, error). Missing file -> ({}, None); bad JSON -> (None, msg)."""
    path = os.path.join(root, ".claude", "guards.json")
    try:
        with open(path, encoding="utf-8") as fh:
            text = fh.read()
    except OSError:
        return {}, None
    try:
        cfg = json.loads(text)
    except ValueError as exc:
        return None, f"{os.path.relpath(path, root)} does not parse: {exc}"
    return cfg, None


def is_skipped(rel):
    parts = rel.split("/")
    name = parts[-1]
    if rel.startswith(SKIP_PREFIXES):
        return True
    if any(p in SKIP_DIR_NAMES for p in parts[:-1]):
        return True
    if name in SKIP_FILENAMES:
        return True
    return any(fnmatch.fnmatch(name, g) for g in SKIP_GLOBS)


def read_bytes(path):
    try:
        with open(path, "rb") as fh:
            return fh.read()
    except OSError:
        return None


def line_counts(root, files):
    """rel -> line count, for every file this gate can and should judge.

    A file that is skipped, unreadable, or binary is simply absent from the
    result -- it is not "0 lines", it was never judged, and an exemption
    naming one of these is a separate defect (see main())."""
    counts = {}
    for rel in files:
        if is_skipped(rel):
            continue
        data = read_bytes(os.path.join(root, rel))
        if data is None:
            continue
        if b"\0" in data[:8192]:
            continue
        counts[rel] = len(data.decode("utf-8", errors="replace").splitlines())
    return counts


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--root", default=".")
    ap.add_argument("--cap", type=int, default=None,
                    help="max lines per tracked text file "
                         "(default 2000, or .claude/guards.json's "
                         '"file_size"."cap")')
    a = ap.parse_args()
    root = os.path.abspath(a.root)

    if shutil.which("git") is None:
        print("cannot judge: git not on PATH", file=sys.stderr)
        return 2

    ls = subprocess.run(["git", "ls-files", "-z"], cwd=root,
                        capture_output=True, text=True)
    if ls.returncode != 0:
        print("cannot judge: not a git repository", file=sys.stderr)
        return 2
    files = [p for p in ls.stdout.split("\0") if p]
    tracked = set(files)

    cfg, err = load_config(root)
    if cfg is None:
        print(f"cannot judge: {err}", file=sys.stderr)
        return 2
    fs_cfg = cfg.get("file_size", {}) if isinstance(cfg, dict) else {}
    if not isinstance(fs_cfg, dict):
        fs_cfg = {}
    cap = a.cap if a.cap is not None else fs_cfg.get("cap", DEFAULT_CAP)
    exempt = fs_cfg.get("exempt") or []

    counts = line_counts(root, files)

    failures = []
    exempt_ok = set()  # paths a valid, still-justified exemption covers
    for e in exempt:
        path = (e.get("path") or "").strip() if isinstance(e, dict) else ""
        reason = (e.get("reason") or "").strip() if isinstance(e, dict) else ""
        if not path:
            failures.append('a .claude/guards.json "file_size" exemption has '
                            "no \"path\"")
            continue
        if not reason:
            failures.append(
                f"{path}: exemption has no reason -- an exemption without "
                "one becomes a blanket exemption")
        if path not in tracked:
            failures.append(
                f"{path}: exemption is for a file that no longer exists "
                "-- remove it")
            continue
        n = counts.get(path)
        if n is None:
            failures.append(
                f"{path}: exemption is for a file this gate does not judge "
                "(binary, or in a skipped path) -- remove it")
        elif n <= cap:
            failures.append(
                f"{path}: exemption is for a file now {n} lines, under the "
                f"cap of {cap} -- it outlived its reason, remove it")
        elif reason:
            exempt_ok.add(path)

    offenders = sorted((rel, n) for rel, n in counts.items()
                       if n > cap and rel not in exempt_ok)

    if not offenders and not failures:
        print(f"{len(counts)} tracked text file(s), all within the "
              f"{cap}-line cap")
        return 0

    for rel, n in offenders:
        print(f"{rel}: {n} lines, cap is {cap}", file=sys.stderr)
    if offenders:
        print(
            "  An agent's Read tool shows 2000 lines by default; the rest is\n"
            "  read only in a call the agent may never make, and the piece it\n"
            "  did not read is where the defect it did not see lives. Split\n"
            "  the file along a natural seam. If splitting is wrong for this\n"
            "  one, add an exemption with a reason to .claude/guards.json:\n"
            '    {"file_size": {"exempt": [{"path": "'
            + (offenders[0][0] if offenders else "path/to/file")
            + '", "reason": "..."}]}}', file=sys.stderr)
    for f in failures:
        print(f, file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
